# Generated by Django 4.2.1 on 2024-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_alter_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images/'),
        ),
    ]
