# Generated by Django 4.2.1 on 2024-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
