# Generated by Django 4.2.1 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
