# Generated by Django 5.0.7 on 2024-07-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_workout_image1_workout_image10_workout_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image9',
        ),
        migrations.CreateModel(
            name='WorkoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workout_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gym_app.workout')),
            ],
        ),
    ]
