# Generated by Django 5.0.7 on 2024-07-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
