# Generated by Django 5.0.7 on 2024-07-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0013_rename_phonenumber_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
