# Generated by Django 4.2.1 on 2024-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0015_coach_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coach_images/'),
        ),
    ]
