# Generated by Django 4.2.1 on 2024-07-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0016_alter_coach_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='membre_images/'),
        ),
    ]
