# Generated by Django 5.0.7 on 2024-07-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0018_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='coachs',
            field=models.ManyToManyField(related_name='workouts', to='gym_app.coach'),
        ),
        migrations.AddField(
            model_name='workout',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym_app.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'En ordre de paiement'), ('refused', 'Paiement refusé')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
