# Generated by Django 4.2.1 on 2024-07-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0019_workout_coachs_workout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
