# Generated by Django 4.2.1 on 2024-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0020_coach_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
